/**
 * O-1 Sovereignty Credit (OSC) System
 * Odyssey-1 AI LLC — Closed-Loop Utility Credit Engine
 *
 * © 2026 Rickey Allan Howard / Howard Jones Bloodline Ancestral Trust
 * All Rights Reserved. Patent Pending: USPTO #63/913,134
 */

import { romanSupabase } from './romanSupabase';

// ============================================================
// CONSTANTS — IMMUTABLE GENESIS PARAMETERS
// ============================================================

export const OSC_CONSTANTS = {
  TOTAL_SUPPLY: 7_600_000_000,          // 7.6 Billion — fixed forever
  VAULT_ALLOCATION: 3_800_000_000,      // 50% — LLC/Trust reserve
  PUBLIC_FORGE: 2_280_000_000,          // 30% — available to public
  EXPANSION_RESERVE: 1_520_000_000,     // 20% — R&D and ecosystem
  BURN_RATE: 0.005,                     // 0.5% per transaction
  GENESIS_PRICE_USD: 1.00,              // $1.00 per OSC at launch
  ORACLE_LOCK_SECONDS: 60,              // 60-second price lock window
  CREDIT_NAME: 'O-1 Sovereignty Credit',
  CREDIT_SYMBOL: 'OSC',
  ISSUER: 'Odyssey-1 AI LLC',
  MANAGING_OFFICER: 'Rickey Allan Howard',
} as const;

// ============================================================
// SERVICE TIERS
// ============================================================

export type ServiceTierId = 'LOGIC' | 'BLUEPRINT' | 'GUARDIAN' | 'SOVEREIGN';

export interface ServiceTier {
  id: ServiceTierId;
  name: string;
  oscCost: number;
  description: string;
  output: string;
  backingIP: string;
}

export const SERVICE_TIERS: Record<ServiceTierId, ServiceTier> = {
  LOGIC: {
    id: 'LOGIC',
    name: 'Logic Credit',
    oscCost: 1,
    description: '5 minutes of AI logic processing and consultation',
    output: 'AI-generated analysis, reasoning, or consultation response',
    backingIP: 'USPTO #63/913,134 — R.O.M.A.N. 2.0 Dual-Hemisphere AI',
  },
  BLUEPRINT: {
    id: 'BLUEPRINT',
    name: 'Blueprint Credit',
    oscCost: 500,
    description: 'One-time access to a patented design or specification',
    output: 'Download of 1 patented design from the 22-innovation portfolio',
    backingIP: 'USPTO #63/913,134 — 22 innovations including hardware specs',
  },
  GUARDIAN: {
    id: 'GUARDIAN',
    name: 'Guardian Credit',
    oscCost: 1000,
    description: 'Full certified custom protocol report',
    output: 'OSHA/legal certified report generated by Odyssey-1 AI',
    backingIP: 'K.A.I.T.S. #63/991,193, PPA_043 Constitutional AI Trust System',
  },
  SOVEREIGN: {
    id: 'SOVEREIGN',
    name: 'Sovereign Credit',
    oscCost: 10000,
    description: 'Direct API integration of Odyssey-1 into a business',
    output: 'Custom Odyssey-1 integration package + setup support',
    backingIP: 'Sovereign Trust Bridge STB-031 + full portfolio',
  },
};

// ============================================================
// LEDGER TYPES
// ============================================================

export interface OscAccount {
  id: string;
  user_id: string;
  balance: number;
  total_acquired: number;
  total_spent: number;
  total_burned: number;
  created_at: string;
  updated_at: string;
}

export interface OscTransaction {
  id: string;
  user_id: string;
  type: 'ACQUIRE' | 'SPEND' | 'BURN' | 'TRANSFER';
  amount: number;
  burn_amount: number;
  service_tier?: ServiceTierId;
  payment_method?: 'USD' | 'BTC' | 'ETH';
  payment_amount?: number;
  payment_currency?: string;
  reference?: string;
  created_at: string;
}

export interface OscSupplyState {
  total_supply: number;
  vault_balance: number;
  public_forge_remaining: number;
  expansion_reserve: number;
  total_burned: number;
  circulating_supply: number;
}

// ============================================================
// CORE LEDGER OPERATIONS
// ============================================================

/**
 * Get OSC account for a user — creates one if it doesn't exist
 */
export async function getOrCreateAccount(userId: string): Promise<OscAccount> {
  const { data: existing } = await romanSupabase
    .from('osc_accounts')
    .select('*')
    .eq('user_id', userId)
    .single();

  if (existing) return existing;

  const { data: created, error } = await romanSupabase
    .from('osc_accounts')
    .insert({
      user_id: userId,
      balance: 0,
      total_acquired: 0,
      total_spent: 0,
      total_burned: 0,
    })
    .select()
    .single();

  if (error) throw new Error(`Failed to create OSC account: ${error.message}`);
  return created;
}

/**
 * Get current OSC balance for a user
 */
export async function getBalance(userId: string): Promise<number> {
  const account = await getOrCreateAccount(userId);
  return account.balance;
}

/**
 * Issue OSC to a user (from Public Forge)
 * Called after payment is confirmed
 */
export async function issueOsc(
  userId: string,
  oscAmount: number,
  paymentMethod: 'USD' | 'BTC' | 'ETH',
  paymentAmount: number,
  paymentCurrency: string,
  reference: string
): Promise<{ success: boolean; newBalance: number; transactionId: string }> {

  // Verify Public Forge has sufficient supply
  const supply = await getSupplyState();
  if (supply.public_forge_remaining < oscAmount) {
    throw new Error('Insufficient Public Forge supply');
  }

  const account = await getOrCreateAccount(userId);

  // Update account balance
  const { error: balanceError } = await romanSupabase
    .from('osc_accounts')
    .update({
      balance: account.balance + oscAmount,
      total_acquired: account.total_acquired + oscAmount,
      updated_at: new Date().toISOString(),
    })
    .eq('user_id', userId);

  if (balanceError) throw new Error(`Balance update failed: ${balanceError.message}`);

  // Record transaction
  const { data: tx, error: txError } = await romanSupabase
    .from('osc_transactions')
    .insert({
      user_id: userId,
      type: 'ACQUIRE',
      amount: oscAmount,
      burn_amount: 0,
      payment_method: paymentMethod,
      payment_amount: paymentAmount,
      payment_currency: paymentCurrency,
      reference,
    })
    .select()
    .single();

  if (txError) throw new Error(`Transaction record failed: ${txError.message}`);

  // Reduce Public Forge supply
  await romanSupabase.rpc('reduce_public_forge', { amount: oscAmount });

  return {
    success: true,
    newBalance: account.balance + oscAmount,
    transactionId: tx.id,
  };
}

/**
 * Execute a service call — the GATEKEEPER
 * Checks balance, burns 0.5%, deducts cost, executes service
 */
export async function executeServiceCall(
  userId: string,
  tierId: ServiceTierId
): Promise<{ approved: boolean; reason?: string; burnAmount: number; newBalance: number }> {

  const tier = SERVICE_TIERS[tierId];
  const account = await getOrCreateAccount(userId);

  // GATE CHECK
  if (account.balance < tier.oscCost) {
    return {
      approved: false,
      reason: `Insufficient OSC. Required: ${tier.oscCost} OSC. Balance: ${account.balance} OSC.`,
      burnAmount: 0,
      newBalance: account.balance,
    };
  }

  // Calculate burn
  const burnAmount = Math.ceil(tier.oscCost * OSC_CONSTANTS.BURN_RATE);
  const totalDeducted = tier.oscCost;
  const newBalance = account.balance - totalDeducted;

  // Update account
  await romanSupabase
    .from('osc_accounts')
    .update({
      balance: newBalance,
      total_spent: account.total_spent + tier.oscCost,
      total_burned: account.total_burned + burnAmount,
      updated_at: new Date().toISOString(),
    })
    .eq('user_id', userId);

  // Record SPEND transaction
  await romanSupabase
    .from('osc_transactions')
    .insert({
      user_id: userId,
      type: 'SPEND',
      amount: tier.oscCost,
      burn_amount: burnAmount,
      service_tier: tierId,
    });

  // Record BURN transaction
  await romanSupabase
    .from('osc_transactions')
    .insert({
      user_id: userId,
      type: 'BURN',
      amount: burnAmount,
      burn_amount: burnAmount,
      service_tier: tierId,
      reference: 'Deflationary burn — 0.5% per transaction',
    });

  // Update global burn counter
  await romanSupabase.rpc('record_burn', { amount: burnAmount });

  return {
    approved: true,
    burnAmount,
    newBalance,
  };
}

/**
 * Get current global supply state
 */
export async function getSupplyState(): Promise<OscSupplyState> {
  const { data, error } = await romanSupabase
    .from('osc_supply')
    .select('*')
    .single();

  if (error || !data) {
    // Return genesis state if not initialized
    return {
      total_supply: OSC_CONSTANTS.TOTAL_SUPPLY,
      vault_balance: OSC_CONSTANTS.VAULT_ALLOCATION,
      public_forge_remaining: OSC_CONSTANTS.PUBLIC_FORGE,
      expansion_reserve: OSC_CONSTANTS.EXPANSION_RESERVE,
      total_burned: 0,
      circulating_supply: 0,
    };
  }

  return {
    ...data,
    circulating_supply: OSC_CONSTANTS.TOTAL_SUPPLY - data.total_burned - data.vault_balance - data.public_forge_remaining - data.expansion_reserve,
  };
}

/**
 * Get transaction history for a user
 */
export async function getTransactionHistory(
  userId: string,
  limit: number = 50
): Promise<OscTransaction[]> {
  const { data, error } = await romanSupabase
    .from('osc_transactions')
    .select('*')
    .eq('user_id', userId)
    .order('created_at', { ascending: false })
    .limit(limit);

  if (error) throw new Error(`Failed to fetch transactions: ${error.message}`);
  return data || [];
}

/**
 * Calculate OSC amount from USD at genesis price
 */
export function usdToOsc(usdAmount: number): number {
  return Math.floor(usdAmount / OSC_CONSTANTS.GENESIS_PRICE_USD);
}

/**
 * Calculate USD value of OSC at genesis price
 */
export function oscToUsd(oscAmount: number): number {
  return oscAmount * OSC_CONSTANTS.GENESIS_PRICE_USD;
}
