import React from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Download, FileText, Mail } from 'lucide-react';

interface Document {
  id: string;
  title: string;
  type: 'project' | 'estimate' | 'agreement';
  content: string;
  status: 'draft' | 'pending' | 'approved';
  createdAt: string;
}

interface PDFExporterProps {
  document: Document;
  bidderInfo?: {
    name: string;
    email: string;
    address: string;
    phone: string;
    city: string;
    state: string;
    zipcode: string;
  };
}

const PDFExporter: React.FC<PDFExporterProps> = ({ document, bidderInfo }) => {
  const generatePDF = () => {
    // Create a new window for PDF generation
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>${document.title}</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
            .header { text-align: center; border-bottom: 2px solid #333; padding-bottom: 20px; margin-bottom: 30px; }
            .title { font-size: 24px; font-weight: bold; color: #333; }
            .subtitle { font-size: 14px; color: #666; margin-top: 5px; }
            .content { white-space: pre-wrap; font-size: 12px; }
            .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ccc; font-size: 10px; color: #666; }
            .bidder-info { background: #f5f5f5; padding: 15px; border-radius: 5px; margin-bottom: 20px; }
            @media print { body { margin: 0; } }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="title">ODYSSEY-1 GENERATED DOCUMENT</div>
            <div class="subtitle">${document.title}</div>
            <div class="subtitle">Generated on ${new Date().toLocaleDateString()}</div>
          </div>
          
          ${bidderInfo ? `
            <div class="bidder-info">
              <h3>Bidder Information</h3>
              <p><strong>Name:</strong> ${bidderInfo.name}</p>
              <p><strong>Email:</strong> ${bidderInfo.email}</p>
              <p><strong>Phone:</strong> ${bidderInfo.phone}</p>
              <p><strong>Address:</strong> ${bidderInfo.address}</p>
              <p><strong>Location:</strong> ${bidderInfo.city}, ${bidderInfo.state} ${bidderInfo.zipcode}</p>
            </div>
          ` : ''}
          
          <div class="content">${document.content}</div>
          
          <div class="footer">
            <p>Document ID: ${document.id} | Status: ${document.status.toUpperCase()} | Type: ${document.type.toUpperCase()}</p>
            <p>Generated by ODYSSEY-1 Bidding Calculator System</p>
          </div>
        </body>
      </html>
    `;

    printWindow.document.write(htmlContent);
    printWindow.document.close();
    printWindow.focus();
    printWindow.print();
  };

  const downloadAsText = () => {
    const content = `${document.title}\n${'='.repeat(document.title.length)}\n\n${document.content}`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${document.title.replace(/\s+/g, '_')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const emailDocument = () => {
    const subject = encodeURIComponent(`Document: ${document.title}`);
    const body = encodeURIComponent(`Please find the attached document:\n\n${document.content}`);
    window.open(`mailto:?subject=${subject}&body=${body}`);
  };

  return (
    <Card className="bg-slate-800/50 border-slate-700">
      <CardHeader>
        <CardTitle className="text-white flex items-center">
          <FileText className="w-5 h-5 mr-2" />
          Export Options
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-3">
        <Button
          onClick={generatePDF}
          className="w-full bg-red-600 hover:bg-red-700"
        >
          <Download className="w-4 h-4 mr-2" />
          Export as PDF
        </Button>
        
        <Button
          onClick={downloadAsText}
          variant="outline"
          className="w-full border-slate-600 text-slate-300 hover:bg-slate-700"
        >
          <Download className="w-4 h-4 mr-2" />
          Download as Text
        </Button>
        
        <Button
          onClick={emailDocument}
          variant="outline"
          className="w-full border-slate-600 text-slate-300 hover:bg-slate-700"
        >
          <Mail className="w-4 h-4 mr-2" />
          Email Document
        </Button>
        
        <div className="text-xs text-slate-400 mt-4">
          <p>• PDF export opens in new window for printing/saving</p>
          <p>• Text download saves as .txt file</p>
          <p>• Email opens default mail client</p>
        </div>
      </CardContent>
    </Card>
  );
};

export default PDFExporter;