# .github/workflows/deploy-edge-functions.yml
name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/functions/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Edge Functions
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link Supabase Project
        env:
          # The link command needs the access token for authentication
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          echo "Linking project to Supabase..."
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
          echo "Project linked successfully."

      - name: Deploy Supabase Edge Functions
        env:
          # The deploy command also needs the access token
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          echo "Starting deployment..."
          # We will keep the project-ref here as a fallback
          supabase functions deploy --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
          echo "Deployment command finished."
