# This is the single, definitive workflow for deploying Supabase Edge Functions.
# It uses the absolute path to the CLI to bypass PATH issues and resolve exit code 127.

name: Deploy Supabase Edge Functions

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Supabase CLI
        shell: bash
        run: |
          set -euxo pipefail
          curl -sL https://github.com/supabase/cli/releases/latest/download/install.sh | sh
          echo "$HOME/.supabase/bin" >> $GITHUB_PATH
          echo "PATH before reload: $PATH"

      - name: Reload PATH
        shell: bash
        run: |
          set -euxo pipefail
          echo "PATH after GITHUB_PATH export: $PATH"
          which supabase || true
          $HOME/.supabase/bin/supabase --version

      - name: Authenticate with Supabase
        shell: bash
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          set -euxo pipefail
          $HOME/.supabase/bin/supabase login --token "$SUPABASE_ACCESS_TOKEN"

      - name: Deploy ai-calculator function
        shell: bash
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: |
          set -euxo pipefail
          which supabase
          $HOME/.supabase/bin/supabase functions deploy ai-calculator --project-id $SUPABASE_PROJECT_ID

      - name: Deploy smarty-address-validation function
        shell: bash
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: |
          set -euxo pipefail
          which supabase
          $HOME/.supabase/bin/supabase functions deploy smarty-address-validation --project-id $SUPABASE_PROJECT_ID
