# This is the single, definitive workflow for deploying Supabase Edge Functions.
# It uses the official Supabase GitHub Action to ensure a robust and reliable installation.

name: Deploy Supabase Edge Functions

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    13|     runs-on: ubuntu-latest
14|     steps:
15|       - name: Checkout repository
16|         uses: actions/checkout@v4
...

      - name: Set up Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

            - name: Deploy All Edge Functions
        working-directory: ${{ github.workspace }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: supabase functions deploy --project-ref $SUPABASE_PROJECT_REF
