# .github/workflows/secret-checker.yml
name: Secret Accessibility Check

on:
  workflow_dispatch: # Allows you to run this manually from the Actions tab

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    name: Validate Secrets are Readable
    
    steps:
      - name: Check for SUPABASE_ACCESS_TOKEN
        env:
          TEST_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          echo "Checking for SUPABASE_ACCESS_TOKEN..."
          if [ -n "$TEST_TOKEN" ]; then
            echo "✅ SUCCESS: SUPABASE_ACCESS_TOKEN is present."
          else
            echo "❌ FAILED: SUPABASE_ACCESS_TOKEN is MISSING or empty."
            exit 1
          fi

      - name: Check for SUPABASE_PROJECT_REF
        env:
          TEST_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          echo "Checking for SUPABASE_PROJECT_REF..."
          if [ -n "$TEST_REF" ]; then
            echo "✅ SUCCESS: SUPABASE_PROJECT_REF is present."
          else
            echo "❌ FAILED: SUPABASE_PROJECT_REF is MISSING or empty."
            exit 1
          fi
