# This is the single, definitive workflow for deploying Supabase Edge Functions.
# It uses the correct 'supabase functions deploy' command without the '--project-id' flag
# and relies on the 'SUPABASE_PROJECT_REF' secret for project linking.
- name: Debug Secrets and Environment
  if: always()
  run: |
    echo "--- DEBUGGING INFORMATION ---"
    echo "Dumping environment state for analysis."
    echo ""
    echo "Step status: ${{ job.status }}"
    echo ""
    echo "Is SUPABASE_ACCESS_TOKEN set? Answer: ${{ env.SUPABASE_ACCESS_TOKEN != '' }}"
    echo "Is SUPABASE_PROJECT_REF set? Answer: ${{ env.SUPABASE_PROJECT_REF != '' }}"
    echo ""
    echo "--- END DEBUGGING ---"
  env:
    SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Supabase CLI
        # This official action handles installation and PATH configuration automatically.
        uses: supabase/setup-cli@v1

      - name: Verify Supabase CLI Installation
        run: supabase --version

      - name: Deploy All Edge Functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          # The CLI uses the Project Ref to link to the correct project.
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: supabase functions deploy


