# This is the single, definitive workflow for deploying Supabase Edge Functions.
# It uses the correct 'supabase functions deploy' command without the '--project-id' flag
# and relies on the 'SUPABASE_PROJECT_REF' secret for project linking.
name: Deploy Supabase Edge Functions

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1

      - name: Deploy All Edge Functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: supabase functions deploy --project-ref $SUPABASE_PROJECT_REF
