# This is the single, definitive workflow for deploying Supabase Edge Functions.
# It uses a robust NPM installation to bypass all previous curl/sh/PATH issues.

name: Deploy Supabase Edge Functions

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        # This step is crucial as it provides the 'npm' command.
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Supabase CLI via NPM
        # This is the new, robust installation method.
        run: npm install -g supabase@latest

      - name: Verify Supabase CLI Installation
        # This step confirms the CLI is installed and available in the path.
        run: supabase --version

      - name: Deploy All Edge Functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: supabase functions deploy --project-id "$SUPABASE_PROJECT_ID"


